- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Create artifact
      set_stats:
        data:
          test_artifact: 31
        per_host: no

